#include <GlobalNames.h>

const QString GLOBAL_STRINGS::PROGRAM_INFO::PROGRAM_NAME("spacePaint");
const QString GLOBAL_STRINGS::PROGRAM_INFO::ORGANIZATION_NAME("DB&DG");
const QString GLOBAL_STRINGS::PROGRAM_INFO::PROGRAM_VERSION("0.1");